LINES = (A_INSTRUCTION | C_INSTRUCTION | <COMMENT_LINE> | <EOL>)+
VALUE = #"\w*"
A_INSTRUCTION = <#"@"> VALUE <EOL>
DEST = #"(M|D|MD|A|AM|AD|AMD)"
COMP = #"[-+|&01ADM!]{1,3}"
JUMP = #"J[EGTQLNMP]{2}"
C_INSTRUCTION = DEST? <EQUALS>? COMP <SEMICOLON>? JUMP? <EOL>
<EOL> = <CARRIAGE_RETURN> | <NEWLINE>
<CARRIAGE_RETURN> = <"\r\n"> 
<NEWLINE> = <"\n">
<EQUALS> = #'='
<SEMICOLON> = #';'
<COMMENT_CHARS> = #"//.*"
<COMMENT_LINE> = <COMMENT_CHARS> <EOL>
<EMPTY_LINE> = ""
