LINES = (A_INSTRUCTION | C_INSTRUCTION | <COMMENT_LINE> | <EOL> | LABEL_SYMBOL)+
VALUE = #"\w*"
SPACE = " "
A_INSTRUCTION = <SPACE>+? <#"@"> VALUE (<SPACE>+ | <COMMENT_CHARS>)? <EOL>
DEST = #"(M|D|MD|A|AM|AD|AMD)"
COMP = #"[-+|&01ADM!]{1,3}"
JUMP = #"J[EGTQLNMP]{2}"
C_INSTRUCTION = <SPACE>+? DEST? <EQUALS>? COMP <SEMICOLON>? JUMP? <SPACE>+? <COMMENT_CHARS>? <EOL>
<EOL> = #"\r?\n"
<EQUALS> = #'='
<SEMICOLON> = #';'
<COMMENT_CHARS> = #"//.*"
<COMMENT_LINE> = <COMMENT_CHARS> <EOL>
<EMPTY_LINE> = ""
SYMBOL = #"\w*"
PAREN = #"[()]"
LABEL_SYMBOL = <SPACE>+? <PAREN> SYMBOL <PAREN> <SPACE>+? <COMMENT_CHARS>? <EOL>
